In [ ]:
!pip install ucimlrepo

Collecting ucimlrepo
  Downloading ucimlrepo-0.0.7-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: pandas>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from ucimlrepo) (2.2.2)
Requirement already satisfied: certifi>=2020.12.5 in /usr/local/lib/python3.12/dist-packages (from ucimlrepo) (2025.10.5)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ucimlrepo) (1.17.0)
Downloading ucimlrepo-0.0.7-py3-none-any.whl (8.0 kB)
Installing collected packages: ucimlrepo
Successfully installed ucimlrepo-0.0.7

In [ ]:
import ucimlrepo
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler

In [ ]:
from ucimlrepo import fetch_ucirepo

# fetch dataset
adult = fetch_ucirepo(id=2)

# data (as pandas dataframes)
X = adult.data.features
y = adult.data.targets

# metadata
print(adult.metadata)

# variable information
print(adult.variables)

{'uci_id': 2, 'name': 'Adult', 'repository_url': 'https://archive.ics.uci.edu/dataset/2/adult', 'data_url': 'https://archive.ics.uci.edu/static/public/2/data.csv', 'abstract': 'Predict whether annual income of an individual exceeds $50K/yr based on census data. Also known as "Census Income" dataset. ', 'area': 'Social Science', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 48842, 'num_features': 14, 'feature_types': ['Categorical', 'Integer'], 'demographics': ['Age', 'Income', 'Education Level', 'Other', 'Race', 'Sex'], 'target_col': ['income'], 'index_col': None, 'has_missing_values': 'yes', 'missing_values_symbol': 'NaN', 'year_of_dataset_creation': 1996, 'last_updated': 'Tue Sep 24 2024', 'dataset_doi': '10.24432/C5XW20', 'creators': ['Barry Becker', 'Ronny Kohavi'], 'intro_paper': None, 'additional_info': {'summary': "Extraction was done by Barry Becker from the 1994 Census database.  A set of reasonably clean records was extracted using the following conditions: ((AAGE>16) && (AGI>100) && (AFNLWGT>1)&& (HRSWK>0))\n\nPrediction task is to determine whether a person's income is over $50,000 a year.\n", 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': 'Listing of attributes:\r\n\r\n>50K, <=50K.\r\n\r\nage: continuous.\r\nworkclass: Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked.\r\nfnlwgt: continuous.\r\neducation: Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool.\r\neducation-num: continuous.\r\nmarital-status: Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse.\r\noccupation: Tech-support, Craft-repair, Other-service, Sales, Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspct, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces.\r\nrelationship: Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried.\r\nrace: White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black.\r\nsex: Female, Male.\r\ncapital-gain: continuous.\r\ncapital-loss: continuous.\r\nhours-per-week: continuous.\r\nnative-country: United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam-USVI-etc), India, Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands.', 'citation': None}}
              name     role         type      demographic  \
0              age  Feature      Integer              Age
1        workclass  Feature  Categorical           Income
2           fnlwgt  Feature      Integer             None
3        education  Feature  Categorical  Education Level
4    education-num  Feature      Integer  Education Level
5   marital-status  Feature  Categorical            Other
6       occupation  Feature  Categorical            Other
7     relationship  Feature  Categorical            Other
8             race  Feature  Categorical             Race
9              sex  Feature       Binary              Sex
10    capital-gain  Feature      Integer             None
11    capital-loss  Feature      Integer             None
12  hours-per-week  Feature      Integer             None
13  native-country  Feature  Categorical            Other
14          income   Target       Binary           Income

                                          description units missing_values
0                                                 N/A  None             no
1   Private, Self-emp-not-inc, Self-emp-inc, Feder...  None            yes
2                                                None  None             no
3    Bachelors, Some-college, 11th, HS-grad, Prof-...  None             no
4                                                None  None             no
5   Married-civ-spouse, Divorced, Never-married, S...  None             no
6   Tech-support, Craft-repair, Other-service, Sal...  None            yes
7   Wife, Own-child, Husband, Not-in-family, Other...  None             no
8   White, Asian-Pac-Islander, Amer-Indian-Eskimo,...  None             no
9                                       Female, Male.  None             no
10                                               None  None             no
11                                               None  None             no
12                                               None  None             no
13  United-States, Cambodia, England, Puerto-Rico,...  None            yes
14                                       >50K, <=50K.  None             no

In [ ]:
#Converte para o pandas
full_df = pd.concat([X, y], axis=1)

In [ ]:
full_df.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [ ]:
full_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             48842 non-null  int64
 1   workclass       47879 non-null  object
 2   fnlwgt          48842 non-null  int64
 3   education       48842 non-null  object
 4   education-num   48842 non-null  int64
 5   marital-status  48842 non-null  object
 6   occupation      47876 non-null  object
 7   relationship    48842 non-null  object
 8   race            48842 non-null  object
 9   sex             48842 non-null  object
 10  capital-gain    48842 non-null  int64
 11  capital-loss    48842 non-null  int64
 12  hours-per-week  48842 non-null  int64
 13  native-country  48568 non-null  object
 14  income          48842 non-null  object
dtypes: int64(6), object(9)
memory usage: 5.6+ MB

In [ ]:
full_df = full_df.rename(columns={"marital-status": "marital_status",
                                  "capital-gain": "capital_gain",
                                  "capital-loss": "capital_loss",
                                  "hours-per-week": "hours_per_week",
                                  "native-country": "native_country",
                                  "education-num": "education_num"})

In [ ]:
full_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             48842 non-null  int64
 1   workclass       47879 non-null  object
 2   fnlwgt          48842 non-null  int64
 3   education       48842 non-null  object
 4   education_num   48842 non-null  int64
 5   marital_status  48842 non-null  object
 6   occupation      47876 non-null  object
 7   relationship    48842 non-null  object
 8   race            48842 non-null  object
 9   sex             48842 non-null  object
 10  capital_gain    48842 non-null  int64
 11  capital_loss    48842 non-null  int64
 12  hours_per_week  48842 non-null  int64
 13  native_country  48568 non-null  object
 14  income          48842 non-null  object
dtypes: int64(6), object(9)
memory usage: 5.6+ MB

In [ ]:
full_df.tail()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
48837,39,Private,215419,Bachelors,13,Divorced,Prof-specialty,Not-in-family,White,Female,0,0,36,United-States,<=50K.
48838,64,NaN,321403,HS-grad,9,Widowed,NaN,Other-relative,Black,Male,0,0,40,United-States,<=50K.
48839,38,Private,374983,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,50,United-States,<=50K.
48840,44,Private,83891,Bachelors,13,Divorced,Adm-clerical,Own-child,Asian-Pac-Islander,Male,5455,0,40,United-States,<=50K.
48841,35,Self-emp-inc,182148,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,60,United-States,>50K.

In [ ]:
# Verificando os dados da coluna workclass
full_df["workclass"].value_counts()

workclass
Private             33906
Self-emp-not-inc     3862
Local-gov            3136
State-gov            1981
?                    1836
Self-emp-inc         1695
Federal-gov          1432
Without-pay            21
Never-worked           10
Name: count, dtype: int64

In [ ]:
full_df["workclass"] = full_df["workclass"].replace({"Private": "private",
                                                     "Self-emp-not-inc": "self-emp-not-inc",
                                                     "Local-gov": "local-gov",
                                                     "State-gov": "state-gov",
                                                     "Self-emp-inc": "self-emp-inc",
                                                     "Federal-gov": "federal-gov",
                                                     "Without-pay": "without-pay",
                                                     "Never-worked": "never-wourked",
                                                     "?": "undefined"})

In [ ]:
full_df["workclass"].value_counts()

workclass
private             33906
self-emp-not-inc     3862
local-gov            3136
state-gov            1981
undefined            1836
self-emp-inc         1695
federal-gov          1432
without-pay            21
never-wourked          10
Name: count, dtype: int64

In [ ]:
# Substituir os valores ausentes da coluna workclass
full_df["workclass"] = full_df["workclass"].fillna('undefined')

In [ ]:
full_df["workclass"].value_counts()

workclass
private             33906
self-emp-not-inc     3862
local-gov            3136
undefined            2799
state-gov            1981
self-emp-inc         1695
federal-gov          1432
without-pay            21
never-wourked          10
Name: count, dtype: int64

In [ ]:
# Verificando os dados da coluna age
full_df["age"].value_counts()

age
36    1348
35    1337
33    1335
23    1329
31    1325
      ...
88       6
85       5
87       3
89       2
86       1
Name: count, Length: 74, dtype: int64

In [ ]:
# Verificando os dados da coluna education
full_df["education"].value_counts()

education
HS-grad         15784
Some-college    10878
Bachelors        8025
Masters          2657
Assoc-voc        2061
11th             1812
Assoc-acdm       1601
10th             1389
7th-8th           955
Prof-school       834
9th               756
12th              657
Doctorate         594
5th-6th           509
1st-4th           247
Preschool          83
Name: count, dtype: int64

In [ ]:
# Verificando os dados da coluna
full_df["occupation"].value_counts()

occupation
Prof-specialty       6172
Craft-repair         6112
Exec-managerial      6086
Adm-clerical         5611
Sales                5504
Other-service        4923
Machine-op-inspct    3022
Transport-moving     2355
Handlers-cleaners    2072
?                    1843
Farming-fishing      1490
Tech-support         1446
Protective-serv       983
Priv-house-serv       242
Armed-Forces           15
Name: count, dtype: int64

In [ ]:
full_df["occupation"] = full_df["occupation"].replace({"Prof-specialty": "prof-specialty",
                                                       "Craft-repair": "craft-repair",
                                                       "Exec-managerial": "exec-managerial",
                                                       "Adm-clerical": "adm-clerical",
                                                       "Other-service": "other-service",
                                                       "Machine-op-inspct": "machine-op-inspct",
                                                       "Transport-moving": "transport-moving",
                                                       "Handlers-cleaners": "handlers-cleaners",
                                                       "Farming-fishing": "farming-fishing",
                                                       "Tech-support": "tech-support",
                                                       "Protective-serv": "protective-serv",
                                                       "Priv-house-serv": "priv-house-serv",
                                                       "Armed-Forces": "armed-forces",
                                                       "?": "undefined"})

In [ ]:
# Substituir os valores ausentes da coluna occupation
full_df["occupation"] = full_df["occupation"].fillna('undefined')

In [ ]:
full_df["occupation"].value_counts()

occupation
prof-specialty       6172
craft-repair         6112
exec-managerial      6086
adm-clerical         5611
Sales                5504
other-service        4923
machine-op-inspct    3022
undefined            2809
transport-moving     2355
handlers-cleaners    2072
farming-fishing      1490
tech-support         1446
protective-serv       983
priv-house-serv       242
armed-forces           15
Name: count, dtype: int64

In [ ]:
full_df.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,state-gov,77516,Bachelors,13,Never-married,adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,private,215646,HS-grad,9,Divorced,handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,private,234721,11th,7,Married-civ-spouse,handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,private,338409,Bachelors,13,Married-civ-spouse,prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [ ]:
full_df["capital_gain"].value_counts()

capital_gain
0        44807
15024      513
7688       410
7298       364
99999      244
         ...
1639         1
2387         1
7262         1
1731         1
6612         1
Name: count, Length: 123, dtype: int64

In [ ]:
# Dados da coluna de paisee
full_df['native_country'].value_counts()

native_country
United-States                 43832
Mexico                          951
Philippines                     295
Germany                         206
Puerto-Rico                     184
Canada                          182
El-Salvador                     155
India                           151
Cuba                            138
England                         127
China                           122
South                           115
Jamaica                         106
Italy                           105
Dominican-Republic              103
Japan                            92
Guatemala                        88
Poland                           87
Vietnam                          86
Columbia                         85
Haiti                            75
Portugal                         67
Taiwan                           65
Iran                             59
Greece                           49
Nicaragua                        49
Peru                             46
Ecuador                          45
France                           38
Ireland                          37
Thailand                         30
Hong                             30
Cambodia                         28
Trinadad&Tobago                  27
Outlying-US(Guam-USVI-etc)       23
Laos                             23
Yugoslavia                       23
Scotland                         21
Honduras                         20
Hungary                          19
Holand-Netherlands                1
Name: count, dtype: int64

In [ ]:
# Padronizaçã de valores categóricos
country_mapping = {
    "United-States": "United States",
    "Outlying-US(Guam-USVI-etc)": "United States",
    "Holand-Netherlands": "Netherlands",
    "Trinadad&Tobago": "Trinidad & Tobago",
    "Hong": "Hong Kong",
}
full_df['native_country'] = full_df['native_country'].replace(country_mapping)

full_df['native_country'].value_counts()

native_country
United States         43855
Mexico                  951
Philippines             295
Germany                 206
Puerto-Rico             184
Canada                  182
El-Salvador             155
India                   151
Cuba                    138
England                 127
China                   122
South                   115
Jamaica                 106
Italy                   105
Dominican-Republic      103
Japan                    92
Guatemala                88
Poland                   87
Vietnam                  86
Columbia                 85
Haiti                    75
Portugal                 67
Taiwan                   65
Iran                     59
Nicaragua                49
Greece                   49
Peru                     46
Ecuador                  45
France                   38
Ireland                  37
Hong Kong                30
Thailand                 30
Cambodia                 28
Trinidad & Tobago        27
Yugoslavia               23
Laos                     23
Scotland                 21
Honduras                 20
Hungary                  19
Netherlands               1
Name: count, dtype: int64

In [ ]:
from scipy.stats import zscore

In [ ]:
print(full_df.columns)

Index(['age', 'workclass', 'fnlwgt', 'education', 'education_num',
       'marital_status', 'occupation', 'relationship', 'race', 'sex',
       'capital_gain', 'capital_loss', 'hours_per_week', 'native_country',
       'income'],
      dtype='object')

In [ ]:
# Converte valore ? para ausestes
full_df.replace('?', np.nan, inplace=True)

In [ ]:
# Colunas numericas para normalização
numeric_cols = full_df.select_dtypes(include=['int64', 'float64']).columns
df_numerico = full_df[numeric_cols].copy() # Copia do dataset original

In [ ]:
# Min e Max Scaler
minmax_scaler = MinMaxScaler()
df_minmax = pd.DataFrame(
    minmax_scaler.fit_transform(df_numerico),
    columns=numeric_cols
)

In [ ]:
# Z-Score
standard_scaler = StandardScaler()
df_standard = pd.DataFrame(
    standard_scaler.fit_transform(df_numerico),
    columns=numeric_cols
)

In [ ]:
# Robust Scaler
robust_scaler = RobustScaler()
df_robust = pd.DataFrame(
    robust_scaler.fit_transform(df_numerico),
    columns=numeric_cols
)

In [ ]:
# Comparação das normalizações
comparacao = pd.DataFrame({
    "Original Média": df_numerico.mean(),
    "Min-Max Média": df_minmax.mean(),
    "Z-Score Média": df_standard.mean(),
    "Robust Média": df_robust.mean()
})

comparacao

                Original Média  Min-Max Média  Z-Score Média  Robust Média
age               3.864359e+01       0.296487   2.275273e-16      0.082179
fnlwgt            1.896641e+05       0.120004  -5.644539e-17      0.095924
education_num     1.007809e+01       0.605206  -9.019624e-17      0.026030
capital_gain      1.079068e+03       0.010791   1.018345e-17   1079.067626
capital_loss      8.750231e+01       0.020088  -9.892491e-18     87.502314
hours_per_week    4.042238e+01       0.402269   4.568003e-17      0.084476
Z_score           4.568003e-17       0.402269   3.287799e-17      0.084476